# Tutorial 2

# Singular Value Decompositions 

In [1]:
##### Ex2.2(a): SVD of matrix
using LinearAlgebra
include("ncon.jl");
d1 = 10; d2 = 6;
A = rand(d1,d2);
F = svd(A); # does the singlar decompostion of A and gives matrices, U, Vt and singular values S.
# check result
Af = F.U*diagm(0 => F.S)*F.Vt;
dA = norm(Af[:]-A[:]);

[6036.299461742217 5831.2411674179775 6211.44757239012 5830.446283165199 6259.965821457549 5531.518561855543 5866.661050740854 5814.0875312081625 5884.580138980194 5736.126405909172; 6187.11854040581 5970.572316322988 6350.706442006354 5994.549550045416 6392.532962870642 5709.738971720053 5981.454932873208 5966.890613730083 6047.372703145649 5849.648054638534; 6435.95885635992 6162.141275422778 6540.616261099312 6132.032330546675 6622.26546638562 5873.752275565159 6164.501374292725 6154.651680302539 6178.310601712952 6037.507365418794; 6161.651114219817 5910.125378938314 6336.801469923162 5943.315134091921 6383.166390539326 5633.751560781261 5961.134622492926 5911.370192511744 5994.661200066202 5878.589607049191; 6025.62795627736 5816.084270774457 6170.925017680887 5832.536927547814 6248.660253254265 5584.778366724179 5814.197653990971 5831.936317419286 5900.920153609995 5706.973907046273; 6183.871588545116 5987.97112616282 6331.03010248963 5975.794736156926 6429.982232716645 5663.1412

In [2]:
size(F.U), size(F.Vt), size(F.S), dA

((10, 6), (6, 6), (6,), 3.0735800000230223e-15)

In [18]:
##### Ex2.2(b): SVD of tensor
d = 10; A = rand(d,d,d);
F = svd(reshape(A,d^2,d));

# checking the shapes of the arrays (not part of the original program)
a = size(F.U)
b = size(F.S)
c = size(F.Vt)
U = reshape(F.U,d,d,d);
# check result
Af = ncon(Any[U,diagm(0 => F.S),F.Vt],
    Any[[-1,-2,1],[1,2],[2,-3]]);
dA = norm(Af[:]-A[:])

4.3474538680081404e-14

In [20]:
a, b, c

((100, 10), (10,), (10, 10))

In [4]:
##### Initialize unitaries and isometries
d1 = 10; d2 = 6;

# d1-by-d1 random unitary matrix U
U = svd(rand(d1,d1)).U;

# d1-by-d2 random isometric matrix W
W = svd(rand(d1,d2)).U;

In [5]:
size(U), size(W)

((10, 10), (10, 6))

In [6]:
diag(U*U')

10-element Array{Float64,1}:
 0.9999999999999994
 0.9999999999999991
 0.9999999999999998
 0.9999999999999996
 0.9999999999999994
 0.9999999999999997
 0.9999999999999997
 0.9999999999999992
 0.9999999999999996
 0.9999999999999997

In [7]:
##### Ex2.2(c): spect. decomp. of matrix
d = 2; A = rand(d,d);
H = 0.5*(A+A'); #random Hermitian
F = eigen(H);
# check result
Hf = F.vectors*diagm(0 => F.values)*F.vectors'
dH = norm(Hf[:]-H[:])

1.1443916996305594e-16

# Spectral decomposition of a tensor 

In [55]:
#  THIS FUNCTION IS NOT SO CLEAR TO ME BECAUSE ONE DOESN'T GET U DAGGER (HERMETIAN U)
# RATHER ONE GETS VECTORS AND IT IS NOT CLEAR HOW TO OBTAIN HERMETIAN IN A MULTIDIMEN-
# SIONAL ARRAY

##### Ex2.2(d): spect. decomp. of tensor
d = 3; A = rand(d,d,d,d);
H = 0.5*(A + permutedims(A,[3,4,1,2])); # WHAT DOES THIS PERMUTAION DEPEND ON?
F = eigen(reshape(H,d^2,d^2));
U = reshape(F.vectors,d,d,d^2);
U_ = reshape(F.vectors, d^2, d, d)
D = diagm(0 => F.values);
# check result
Hf = ncon(Any[U,D,U],
    Any[[-1,-2,1],[1,2],[-3,-4,2]]);
#Hf = ncon(Any[U_,D,U],
#    Any[[1,-1,-2],[1,2],[-3,-4,2]]);
dH = norm(Hf[:]-H[:])

9.173601550346555e-15

In [16]:
size(F.vectors), size(F.values), size(F.vectors')

((9, 9), (9,), (9, 9))

In [28]:
#size(U') # THIS GIVES AN ERROR BECAUSE ONE NEEDS TO USE PRMUTEDIMS FOR HIGHER DIMENSIONS

# QR decomposition (useful in concept of guage in tensors)

In [15]:
##### Ex2.2(f): QR decomp of matrix
d1 = 10; d2 = 6;
A = rand(d1,d2);
F = qr(A);
# check result
Af = F.Q*F.R;
dA = norm(Af[:]-A[:])

1.8687279961009696e-15

In [16]:
##### Ex2.2(g): QR decomp of tensor
d = 10;
A = rand(d,d,d);
F = qr(reshape(A,d^2,d));
Q = reshape(Array(F.Q),d,d,d);
# check result
Af = ncon(Any[Q,F.R],Any[[-1,-2,1],[1,-3]]);
dA = norm(Af[:]-A[:])

1.1916210198987908e-14

# Frobenious norm

In [6]:
##### Ex2.3(c)
d = 10;
A = rand(10,10,10,10,10);
# frobenus norm
frobA0 = sqrt(ncon(Any[A,conj(A)],Any[collect(1:ndims(A)),collect(1:ndims(A))]));
# equivalent frobenus norm
frobA1 = sqrt(sum(abs.(A[:]).^2));
# also equivalent frobenus norm
frobA2 = norm(A);

In [7]:
norm(frobA1-frobA2), frobA1, frobA2, frobA0

(0.0, 182.59926937948913, 182.59926937948913, 182.59926937948913)

In [12]:
collect(1:ndims(A))

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

# T2.4: Restricted rand tensor approximation

In [35]:
##### Ex2.4(a): take SVD
d = 10; A = rand(d,d,d,d,d);
F = svd(reshape(A,d^3,d^2));
U = reshape(F.U,d,d,d,d^2);
Vh = reshape(F.Vt,d^2,d,d);

In [36]:
size(U),size(F.S), size(Vh) 

((10, 10, 10, 100), (100,), (100, 10, 10))

In [45]:
##### truncate SVD
chi = 8;
Vhtilda = Vh[1:chi,:,:];
Stilda = diagm(0 => F.S[1:chi]);
Utilda = U[:,:,:,1:chi];
B = ncon(Any[Utilda,Stilda,Vhtilda],Any[[-1,-2,-3,1],[1,2],[2,-4,-5]]);
##### compare
epsAB = norm(A-B) / norm(A)

0.469148268473553

In [47]:
C = ncon(Any[Vhtilda, Stilda, Utilda], Any[[1, -1, -2], [1, 2], [-3, -4, -5, 2]]);
epsAC = norm(A-C)/norm(A)

0.5307673130357585

In [16]:
size(Vh)

(100, 10, 10)

In [18]:
size(Vhtilda), size(Stilda), size(Utilda)

((8, 10, 10), (8, 8), (10, 10, 10, 8))

In [19]:
epsAB

0.46775653009324497

# Effective Rank of a Tensor 

In [75]:
##### Ex2.4(d): effective rank
# Generate toeplitz matrix (each diagonal is the decending order is a constant)
d = 500;
A = diagm( 1 => ones(d-1)) +
    diagm(-1 => ones(d-1));
A = A / norm(A) #normalize
# compute effective rank to accuracy 'deltaval'
deltaval = 1e-2;
F = svd(A);
r_delta = sum(F.S .> deltaval)
eps_err = sqrt.(sum(F.S[r_delta+1:end] .^2))

31.591137997862624

0.04040991568438646

In [89]:
B = diagm( 0 => ones(5)) 
N = (norm(B))^2
#B = B/norm(B)
#print(B)
#probability_matrix = B^2

5.000000000000001

# Exercise sheet 2

In [56]:
# b).
d1 = 10
d2 = 8
A = rand(d1, d1, d2, d2);
print(norm(A))
N = norm(A)
A = A/N; # Normalized tensor
norm(A)

46.22542710476335

1.0

In [57]:
#c)
# SVD
F = svd(reshape(A, d1^2, d2^2));
s_values = F.S
#s_values_squared = (F.S)^2;
# We need to calculate the square root of the sum of squares of the singular values
# The sum of square of singular values is the dot product 
value = sqrt(s_values'*s_values)

0.9999999999999999

In [60]:
#d).
# compute effective rank to accuracy 'deltaval'
deltaval = 1e-1;
r_delta = sum(s_values .> deltaval)

4

In [61]:
#e).
eps_err = sqrt.(sum(s_values[r_delta+1:end] .^2))

0.45795473314559476

f) Construct the optimal restricted rank approximation to A' via the truncated SVD. Compute the truncation error ε of this approximation and check that your answer is consistent with part (e).


In [62]:
# To calculate the truncation error we need to calculate the matrix which results from the truncation
# from the matrices obtained from the SVD.
U = F.U;
S = diagm(F.S);
Vt = F.Vt;

In [63]:
size(U), size(Vt), size(Vt)

((100, 64), (64, 64), (64, 64))

In [64]:
# Truncating
U = reshape(U, d1, d1, d2^2);
Vt = reshape(Vt, d2^2, d2, d2)
U_tr = U[:, :, 1:r_delta];
Vt_tr = Vt[1:r_delta, :, :];
S_tr = diagm(F.S[1:r_delta]);

In [65]:
size(U_tr), size(S_tr), size(Vt_tr)

((10, 10, 4), (4, 4), (4, 8, 8))

In [66]:
# Now we need to do the contracrtion of these three matrices 
B = ncon(Any[U_tr,S_tr,Vt_tr],Any[[-1,-2,1],[1,2],[2,-3,-4]]);
size(B)

(10, 10, 8, 8)

In [68]:
err_1 = sqrt.(sum((A_normalized[:] - B[:]) .^2))


0.26690321780323184

# Official Solutions 

In [2]:
##### Pb.2(a): solutions
using LinearAlgebra
# ensure 'ncon.jl' in working dir
include("ncon.jl");

##### Define matrix A
#THE FIRST MISTAKE WHICH I DID IS THAT I DID NOT CONSIDER THAT 
# THE TENSOR NEEDS TO BE CREATED IN A MANNER AS DEFINED IN THE
# EXERCISE SHEET.
d1 = 10;
d2 = 8;
A = zeros(d1,d1,d2,d2);
for ni = 1:d1
    for nj = 1:d1
        for nk = 1:d2
            for nl = 1:d2
                A[ni,nj,nk,nl] = sqrt(ni + 2*nj + 3*nk + 4*nl);
            end
        end
    end
end


[5537.219441723589 6125.9660516838585 5992.12678101195 6155.093471129699 5690.469005823615 6118.669305972651 5866.980067763507 5245.801124075184 5606.884651338412 5739.135128769934; 5532.169678981884 6107.099486767685 5990.731933027478 6174.934754779376 5681.54514627241 6076.9931182824685 5837.662847236939 5235.557971881938 5567.862676359368 5706.560716885889; 5602.276715392664 6212.876877208657 6012.100344283798 6223.489754454915 5760.67323100333 6170.358604399735 5932.275697430724 5299.937111140773 5690.164224033445 5813.373624605823; 5560.013969005389 6132.263251464878 6103.234064241658 6161.723797204347 5697.658890339639 6131.218145593122 5884.621431921146 5295.692455300436 5591.544527628927 5723.714816840177; 5656.023325191478 6274.878895604363 6057.697431271672 6267.990426298381 5803.71954552955 6206.325896402198 5961.736538660834 5324.522920381241 5709.315622840999 5825.971115386716; 5478.166502272311 6045.0461214178085 5916.493321754746 6089.5453138755065 5642.089184139102 5997

In [4]:
# b).
N = norm(A)
print(N)
A_normalized = A/N; # Normalized tensor

554.2562584220408

In [5]:
#c)
# reshaping 
# SVD
F = svd(reshape(A_normalized, d1^2, d2^2));
s_values = F.S
#s_values_squared = (F.S)^2;
# We need to calculate the square root of the sum of squares of the singular values
# The sum of square of singular values is the dot product 
value = sqrt(s_values'*s_values)

# THE SQUARE ROOT OF THE SUM OF THE SINGULAR VLUES SQUARED IS EQUAL TO THE TENSOR NORM

1.0

In [6]:
#d).
# compute effective rank to accuracy 'deltaval'
deltaval = 1e-4;
r_delta = sum(s_values .> deltaval)

3

In [7]:
#e).
err_0 = sqrt.(sum(s_values[r_delta+1:end] .^2))

1.0484615133223257e-5

In [8]:
##### optimal restricted rank approximation
B = F.U[:,1:r_delta]*diagm(0 => F.S[1:r_delta])*F.Vt[1:r_delta,:];
B = reshape(B,d1,d1,d2,d2);
err_1 = sqrt.(sum((A_normalized[:] - B[:]) .^2));
# compare
[err_0,err_1]

2-element Array{Float64,1}:
 1.0484615133223257e-5
 1.048461513321334e-5

In [9]:
# contracting by ncon function

U_tr = reshape(F.U, d1, d1, d2^2)[:, :, 1:r_delta];
Vt_tr = reshape(F.Vt, d2^2, d2, d2)[1:r_delta, :, :];
S_tr = diagm(F.S[1:r_delta]);
B = ncon(Any[U_tr,S_tr,Vt_tr],Any[[-1,-2,1],[1,2],[2,-3,-4]]);

# using ncon in a different order
#B = ncon(Any[Vt_tr,S_tr,U_tr],Any[[1,-1,-2],[1,2],[-3,-4,2]]); THIS DOES NOT GIVE SENSIBLE RESULTS

err_ncon = sqrt.(sum((A_normalized[:] - B[:]) .^2));

# compare
[err_ncon,err_1]

2-element Array{Float64,1}:
 1.048461513321334e-5
 1.048461513321334e-5